### ISSUE TITLE
Questions, 

### ISSUE THREAD

**Issue by Kiho-Kwon** [Chuanhsing/PoeCharm#1]
This is not an issue.
I am writing here as this is the only way to contact you.

I would like help in creating a multilingual version of a similar type.
I would like to know how to apply the language without changing the actual lua file. Can you help?

**Comment by Chuanhsing** [comment]
use sqlite3 to open PoeCharm/Pob/resources.db, change the config translate_tw to translate_{lang} and create a table

**Comment by Kiho-Kwon** [comment]
Thanks, I'll try.
