### ISSUE TITLE
更好的数据库维护方式

### ISSUE THREAD

**Issue by me1ting** [Chuanhsing/PoeCharm#10]
你好，我是Chrome插件POE-CN-EXPORT的开发者，用于将腾讯服的BD数据导出供原版POB（主要是配合PoeCharm）使用。其主要思路是将数据从中文转换为英文。相比于国服版POB，只需要处理核心字段的翻译（主要是词缀），后期可维护性更高。

其中就用到了PoeCharm的翻译资源，在开发过程中我发现了PoeCharm的一些漏翻译、错误翻译，但苦于现有的数据库是db文件，因此难以以Pull Request的方式提交更新。

因此想要探讨一下能否使用更好的数据库维护方式：

- 翻译资源进行更细致的区分，如非装备类词缀可以丢弃，如对"{}% 攻击"与“{} 攻击”进行区分处理
- 使用更好的可维护性格式存储，如json，xls，properties等
- 使用脚本生成db文件

或者说独立一个项目来供类似的项目使用？每个项目只要基于现有的数据库，按照自己的需求来使用即可。

**Comment by Chuanhsing** [comment]
已改為 csv 格式
