### ISSUE TITLE
作者你好，请问能解决一下poecharm在高分辨率下pob字特别小的问题吗

### ISSUE THREAD

**Issue by mlzzen** [Chuanhsing/PoeCharm#21]
非常感谢

**Comment by clivelee** [comment]
这个问题也困扰很久了，不知道怎么调整

**Comment by f111fei** [comment]
![image](https://github.com/Chuanhsing/PoeCharm/assets/7069719/80c7adc3-19cb-44e1-b302-3e0a107ec7f8)
这样设置就行了
