### ISSUE TITLE
PoeCharm2 渲染模糊

### ISSUE THREAD

**Issue by laymanal** [Chuanhsing/PoeCharm#45]
Windows 11 23H2 1080P 100% DPI PoeCharm 2.6.0

![PoeCharm2](https://github.com/Chuanhsing/PoeCharm/assets/1684121/205bc709-088d-40de-a2f0-126eeb63bedd)

请关爱残障人士😂
![CrazyBlindGIF](https://github.com/Chuanhsing/PoeCharm/assets/1684121/512501db-f2f3-4f8f-903c-fec1a4c3cfe5)

**Comment by ZdDroid** [comment]
请问显示器的分辨率以及DPI 是怎么设置的呢(最好提供截图)
从图片上看确实挺模糊的

这是本机的参考图  分辨率:4K DPI:175%
![RK93(~03{_ 1UIO%2MIZDF8](https://github.com/Chuanhsing/PoeCharm/assets/43038779/c0e04123-10a7-417d-85e2-3b1e15cf0a5d)
