### ISSUE TITLE
关于界面本地化 About interface localization

### ISSUE THREAD

**Issue by Rayforward** [Chuanhsing/PoeCharm#6]
你好，我是你所开发的这款优秀工具的忠实用户，我发现随着pob版本的更新，其包含了越来越多poecharm没有本地化的条目和GUI（经过对db文件的浏览，发现其中“综合DPS这一条目是由于英文Combine DPS缺少了':'号导致本地化未生效”），请指教下是否对此方面有跟进本地化的计划？我对此也有出一份支援之力的意愿，有点汉化癖好的无名网友敬上

Hi, I am a loyal user of this excellent tool you developed. I found that as the POB version was updated, it included more and more items and GUIs that poecharm had not localized (after browsing the DB file, It is found that "the item '综合DPS' is due to the lack of the" : "sign of English 'Combine DPS', which leads to the failure of localization"), please kindly advise whether there is any plan to follow up localization in this aspect. I also have a willingness to support this force,  unknown netizens with a little bit of localization love here XD

**Comment by Rayforward** [comment]
> you can list like this and I will combine next patch:
> 
> Combine DPS,综合DPS

Start to work~

**Comment by Chuanhsing** [comment]
已更新至 v20211024 版本
中文專案用中文就可以了
